### ISSUE TITLE
What is meant by emulating rpi on qemu

### ISSUE THREAD

**Issue by dhiraj113** [dhruvvyas90/qemu-rpi-kernel#12]
This probably is a very dumb question, but nevertheless I do ask it here. What exactly is meant by emulating rpi-kernel on qemu. Is it any different from emulating ARM ISA using qemu. Does qemu emulation, by any chance, also emulate the Rasberry Pi's BCM2835 board i.e. does it emulate the peripheral devices, memory mapped I/O registers etc.

**Comment by dhruvvyas90** [comment]
@dhiraj113: Sorry for the delayed answer. Emulating rpi-kernel on Qemu means it allows users to mimic Raspberry pi's behaviour on their native computers. As far as my understanding goes, these particular kernels are configured for versatilepb board (not BCM2835) and hence it shouldn't emulate BCM2835's memory mapped I/O registers and peripheral devices. I may be wrong here due to my limited understanding of how qemu actually works. The reason why these kernels are speciafically compiled for versatilepb ie because Qemu natively doesn't support emulating Rpi platform. I hope I did justice to your queries.
