### ISSUE TITLE
How to start the X11 GUI? Stuck on "No session for pid <PID>."

### ISSUE THREAD

**Issue by cirosantilli** [dhruvvyas90/qemu-rpi-kernel#20]
I've managed to login on a shell after reading the wiki: https://github.com/dhruvvyas90/qemu-rpi-kernel/wiki/Emulating-Jessie-image-with-4.x.xx-kernel as in http://raspberrypi.stackexchange.com/questions/165/emulation-on-a-linux-pc/53991#53991 , thanks!

How to get the GUI working now?

I've tried: `startx`, and it does start and show the GUI, but everything is frozen and there is a popup saying: `No session for pid <PID>`.

Ubuntu 16.04 host, Raspbian Jessie 2016-05.

![screenshot from 2016-08-25 19-34-06 rpi no session for pid](https://cloud.githubusercontent.com/assets/1429315/17981354/411cce1c-6afb-11e6-8b9d-338c165612e6.png)

**Comment by EdgarOliveira** [comment]
Hello,

Try following my script: https://github.com/dhruvvyas90/qemu-rpi-kernel/issues/22
Maybe didn't set all file necessary!

**Comment by cirosantilli** [comment]
@EdgarOliveira hmm, that seems to be what I've done. The only modifications to the image were to comment out `ld.so.preload` and `fstab` no?

So your GUI works fine? What are the exact versions of everything you are using:

- Raspbian
- Host Distro
- QEMU

**Comment by EdgarOliveira** [comment]
I just tried this version:

2016-05-27-raspbian-jessie
DietPi_v130_RPi-armv6-(Jessie)

I am using Lubuntu 16.04 4.4.0-34-generic. I only installed qemu-system->QEMU full system emulation binaries and another reason which I don't understand I can't find version of this installation. I will search more deep and i will report!

**Comment by dhruvvyas90** [comment]
@cirosantilli: Can you check if this problem persists with the newer kernel added on the repo recently ? 4.4.13 ?

**Comment by cirosantilli** [comment]
@dhruvvyas90 still same. You don't reproduce?

**Comment by dhruvvyas90** [comment]
@cirosantilli: I don't seem to reproduce the same issue on my computer. I'm running 14.04 Lubuntu on a virtual machine on my mac which is different than your configuration though.

**Comment by saildata** [comment]
@cirosantilli That looks like a [PAM](https://wiki.archlinux.org/index.php/PAM) security issue/pop-up. 

Can you check for the file, `/etc/pam.d/login`? PID 138 tells you that it's a very early stage process that's failing, like something in the PAM libraries.

If you are able to drop back down to your shell, e.g. with `ctrl+F2`:
 - filter the systemd journal to just that PID with the command `journalctl --this-boot _PID=138`
 - change the process number as needed. 
 - review the output and cleanup any personal info before posting online. It may be sufficient to post a snippet instead of the entire thing.

Hopefully those get you the information you need to resolve the problem. Good luck!

**Comment by cirosantilli** [comment]
@saildata

I cannot find how to drop back to a shell:

- Ctrl + F2 does nothing
- Ctrl + Alt + F2 is captured by host
- Ctrl + Alt + 2 then `sendkey ctrl+alt+f2` does nothing.

I tried to run `journalctl` on a second login, but the files don't persist, not sure why. 

`/etc/pam.d/login`:

```
#
# The PAM configuration file for the Shadow `login' service
#

# Enforce a minimal delay in case of failure (in microseconds).
# (Replaces the `FAIL_DELAY' setting from login.defs)
# Note that other modules may require another minimal delay. (for example,
# to disable any delay, you should add the nodelay option to pam_unix)
auth       optional   pam_faildelay.so  delay=3000000

# Outputs an issue file prior to each login prompt (Replaces the
# ISSUE_FILE option from login.defs). Uncomment for use
# auth       required   pam_issue.so issue=/etc/issue

# Disallows root logins except on tty's listed in /etc/securetty
# (Replaces the `CONSOLE' setting from login.defs)
#
# With the default control of this module:
#   [success=ok new_authtok_reqd=ok ignore=ignore user_unknown=bad default=die]
# root will not be prompted for a password on insecure lines.
# if an invalid username is entered, a password is prompted (but login
# will eventually be rejected)
#
# You can change it to a "requisite" module if you think root may mis-type
# her login and should not be prompted for a password in that case. But
# this will leave the system as vulnerable to user enumeration attacks.
#
# You can change it to a "required" module if you think it permits to
# guess valid user names of your system (invalid user names are considered
# as possibly being root on insecure lines), but root passwords may be
# communicated over insecure lines.
auth [success=ok new_authtok_reqd=ok ignore=ignore user_unknown=bad default=die] pam_securetty.so

# Disallows other than root logins when /etc/nologin exists
# (Replaces the `NOLOGINS_FILE' option from login.defs)
auth       requisite  pam_nologin.so

# SELinux needs to be the first session rule. This ensures that any 
# lingering context has been cleared. Without out this it is possible 
# that a module could execute code in the wrong domain.
# When the module is present, "required" would be sufficient (When SELinux
# is disabled, this returns success.)
session [success=ok ignore=ignore module_unknown=ignore default=bad] pam_selinux.so close

# This module parses environment configuration file(s)
# and also allows you to use an extended config
# file /etc/security/pam_env.conf.
# 
# parsing /etc/environment needs "readenv=1"
session       required   pam_env.so readenv=1
# locale variables are also kept into /etc/default/locale in etch
# reading this file *in addition to /etc/environment* does not hurt
session       required   pam_env.so readenv=1 envfile=/etc/default/locale

# Standard Un*x authentication.
@include common-auth

# This allows certain extra groups to be granted to a user
# based on things like time of day, tty, service, and user.
# Please edit /etc/security/group.conf to fit your needs
# (Replaces the `CONSOLE_GROUPS' option in login.defs)
auth       optional   pam_group.so

# Uncomment and edit /etc/security/time.conf if you need to set
# time restrainst on logins.
# (Replaces the `PORTTIME_CHECKS_ENAB' option from login.defs
# as well as /etc/porttime)
# account    requisite  pam_time.so

# Uncomment and edit /etc/security/access.conf if you need to
# set access limits.
# (Replaces /etc/login.access file)
# account  required       pam_access.so

# Sets up user limits according to /etc/security/limits.conf
# (Replaces the use of /etc/limits in old login)
session    required   pam_limits.so

# Prints the last login info upon succesful login
# (Replaces the `LASTLOG_ENAB' option from login.defs)
session    optional   pam_lastlog.so

# Prints the message of the day upon succesful login.
# (Replaces the `MOTD_FILE' option in login.defs)
session    optional   pam_exec.so type=open_session stdout /bin/uname -snrvm
session    optional   pam_motd.so

# Prints the status of the user's mailbox upon succesful login
# (Replaces the `MAIL_CHECK_ENAB' option from login.defs). 
#
# This also defines the MAIL environment variable
# However, userdel also needs MAIL_DIR and MAIL_FILE variables
# in /etc/login.defs to make sure that removing a user 
# also removes the user's mail spool file.
# See comments in /etc/login.defs
session    optional   pam_mail.so standard

# Sets the loginuid process attribute
session    required     pam_loginuid.so

# Standard Un*x account and session
@include common-account
@include common-session
@include common-password

# SELinux needs to intervene at login time to ensure that the process
# starts in the proper default security context. Only sessions which are
# intended to run in the user's context should be run after this.
session [success=ok ignore=ignore module_unknown=ignore default=bad] pam_selinux.so open
# When the module is present, "required" would be sufficient (When SELinux
# is disabled, this returns success.)
```

**Comment by saildata** [comment]
@cirosantilli Thanks for the detailed information. There is so many things it could be, I know it's frustrating - been there before!  
  
Since it's such an oddball item, that others aren't really seeing, myself included, that leads me to believe that it's something with your image file or otherwise a local problem. Is there another image you can try? Have you tried it on bare-metal (actual Pi?) to see if it's a QEMU issue, or hardware compatability?

You can also boot with parameters, `loglevel=`, with higher values producing more verbose logs (like 6 or 7) see if anything sticks out to you.
 
For the persistense of `journalctl`, it would depend on where you're storing your `/var` directory for the QEMU process. If it's in memory, or in some temporary place that's overwritten each time then it won't stick around for long : ) It is supposed to be persistent, like on my laptop right now, I have the logs (zipped) going back to day 1 I believe. That's the way systemd seems to work. 

For the keyboard shortcuts, maybe that has to do with keyboard layout, and I'm just used to those shortcuts? 

When you get a chance:  
  
- [ ] Is it reproducible with another image? (Or computer?)
- [ ] Is it reproducible on an actual RPI?
- [ ] Can we find out what the actual process is? My initial theory was wrong - you obviously have the PAM file.

Good luck --

**Comment by dhruvvyas90** [comment]
@cirosantilli: Any progress on what @saildata suggested ?

**Comment by cirosantilli** [comment]
@saildata I commend you for your patience...

> Is it reproducible with another image? (Or computer?)

Which other image? I have already successfully run Ubuntu and buildroot images with X11 on my QEMU.

> it would depend on where you're storing your /var directory for the QEMU process

This is what I'm doing step by step: http://raspberrypi.stackexchange.com/questions/165/emulation-on-a-linux-pc/53991#53991

I don't know how to tell QEMU to write things to disk, e.g. `touch a` does not persist.

> Is it reproducible on an actual RPI

The PI does not boot up with the modified image, serial connection shows nothing.

> Can we find out what the actual process is?

How? :-(

**Comment by saildata** [comment]
@cirosantilli Thank you for your patience as well! Sorry it's not working out for you. It sounds like the image is mounted read only, but from your post it looks like you're doing the correct command for rw access. I'd suggest trying a different method, from one of the following two tutorials...

In the past, I followed [this guide](https://lionfacelemonface.wordpress.com/2015/04/18/raspberry-pi-build-environment-in-no-time-at-all/). Looking back at the guide, it reminded me that I did all my work from the command line. It did change the underlying img file, so that may be worth checking out for persistence.

Another possibility that I just found, which I didn't think about before, is to use a VNC server on the RPI and forward the relevant ports. Then you can use a VNC viewer to connect to the running QEMU session. I've used both [RealVNC](https://www.realvnc.com/) and [Remmina](https://github.com/FreeRDP/Remmina). I think I remember using a PPA for that one as it was from a Linux Mint host. The [tutorial](https://xbu.me/emulating-raspberry-pi-with-qemu/) I found seems to walk through the required steps.

When you say that it doesn't boot with the modified image, you are changing the `ld.so.preload` and `fstab` back to their original state, correct?  

Good luck with the tutorials, let us know how it goes!

**Comment by cirosantilli** [comment]
@saildata 

> When you say that it doesn't boot with the modified image, you are changing the ld.so.preload and fstab back to their original state, correct? 

No, the if I did wouldn't the image be identical to the official one and would just work?

> Another possibility that I just found, which I didn't think about before, is to use a VNC server on the RPI and forward the relevant ports.

True! I have already used VNC before ;-) But even simpler, I'll just forward SSH into it!

I'll reply later with what I observe.

**Comment by saildata** [comment]
> No, if I did wouldn't the image be identical to the official one and would just work?

Hopefully I understand your response -- correct me if this is wrong. You do need a valid linker/loader (the `ld.so.preload` file) for the image to boot. In other words - the revisions you make so that QEMU can boot the image need to be reverted back to their original state before writing the image to an SD card so that the Rpi can use it. If you were to write the image back to an SD card and try to boot it without the correct `ld.so.preload` file, it would fail.  
The same goes for the `fstab` file -- it describes the filesystems that are used, so it's very important that this is also reverted to it's original state.    
  
> I'll reply later with what I observe.

Awesome -- let us know how it works out : )

**Comment by cirosantilli** [comment]
The `-append "init=/bin/bash"` was definitely not helping. :-)

**Comment by EdgarOliveira** [comment]
Hello,

I am trying use qemu to test images iso just like Lubuntu, Ubuntu and
debian. I can run iso which live CD but the performance it is very bad! Do
you advice this program for this purpose or suggest any software?

I tested with qemu because I like this program because I can using it
through terminal.

Thanks

**Comment by cirosantilli** [comment]
@EdgarOliveira I don't think we can get super good performance on ARM emulation from x86, because x86 has hardware support for emulation.

**Comment by EdgarOliveira** [comment]
@cirosantilli
What software suggest to execute virtual machine from terminal for x86?

**Comment by EdgarOliveira** [comment]
Hello,

I have a problem when I tried do the task on this video:
https://www.youtube.com/watch?v=Ny-7pRx_yHk
Any idea how can I solve this issue?

Please read the describition video to know more about the problem.

Thanks

2016-10-03 0:25 GMT+01:00 Edgar Oliveira Dev <edgaroliveira.dev@gmail.com>:

> Hello,
>
> I am trying use qemu to test images iso just like Lubuntu, Ubuntu and
> debian. I can run iso which live CD but the performance it is very bad! Do
> you advice this program for this purpose or suggest any software?
>
> I tested with qemu because I like this program because I can using it
> through terminal.
>
> Thanks
>

**Comment by EdgarOliveira** [comment]
Hello,

Do you received this email?
Thanks

2017-12-02 22:28 GMT+00:00 Edgar Oliveira Dev <edgaroliveira.dev@gmail.com>:

> Hello,
>
> I have a problem when I tried do the task on this video:
> https://www.youtube.com/watch?v=Ny-7pRx_yHk
> Any idea how can I solve this issue?
>
> Please read the describition video to know more about the problem.
>
> Thanks
>
>
> 2016-10-03 0:25 GMT+01:00 Edgar Oliveira Dev <edgaroliveira.dev@gmail.com>
> :
>
>> Hello,
>>
>> I am trying use qemu to test images iso just like Lubuntu, Ubuntu and
>> debian. I can run iso which live CD but the performance it is very bad! Do
>> you advice this program for this purpose or suggest any software?
>>
>> I tested with qemu because I like this program because I can using it
>> through terminal.
>>
>> Thanks
>>

**Comment by cirosantilli** [comment]
@EdgarOliveira I saw, but I don't know enough about this / don't have time, sorry.

However, I will recommend this: focus instead on ` -M raspi2` as mentioned at: https://raspberrypi.stackexchange.com/questions/165/emulation-on-a-linux-pc/53991#53991 which "dispenses" this custom kernel (but GUI not working yet).
