### ISSUE TITLE
Support for IPv6 ?

### ISSUE THREAD

**Issue by alexAubin** [dhruvvyas90/qemu-rpi-kernel#27]
Hi there,

this is some awesome work here and I'm very glad to be able to emulate a RaspberryPi thanks to Qemu and these kernels 👍 !

However I noticed that for my application, I need ipv6 enabled. Currently, loading the ipv6 module fails during boot an I get messages such as : 
```
ipv6: version magic '4.4.34+ mod_unload modversions ARMv6 ' should be '4.4.34+ mod_unload ARMv6 p2v8 '
```

I'm a huge noob when it comes to kernels, but somehow this sounds related to the IPv6 flags not being set [here](https://github.com/dhruvvyas90/qemu-rpi-kernel/blob/master/tools/config_file_3.10.25#L479) ?

Would that be easy to include the flags in the next kernels, or do I definitely need to recompile it on my side ? 😕

**Comment by dhruvvyas90** [comment]
A new PR has been merged which consists a couple of more advanced kernels. May be you can try them and see if any of them suits your requirement.

**Comment by alexAubin** [comment]
Eeeeh, unfortunately I was already trying these kernels (and had a few tries with the less recent ones), but always end up with this issue. I'm actually not even sure if that's related to my particular use case, or if that's a kernel issue, or a raspbian image issue :confused:.

**Comment by dhruvvyas90** [comment]
@alexAubin: Let me try to build a new kernel with slightly altered configuration. I will get back to you on this issue very soon.

**Comment by alexAubin** [comment]
Okay, thank you so much !

**Comment by phildubach** [comment]
I encountered the same issue. Workaround below.

I'm running the `kernel-qemu-4.4.34-jessie` kernel on `2016-11-25-raspbian-jessie-lite.img` or `2017-01-11-raspbian-jessie-lite.img` with the same results.
None of the modules are loaded due to version magic mismatch.

As can be seen in `/var/log/syslog`, there are a number of failed module loads:
```
pi@raspberrypi:~ $ grep 'version magic' /var/log/syslog | cut -f6- -d' ' | sort | uniq
evdev: version magic '4.4.34+ mod_unload modversions ARMv6 ' should be '4.4.34+ mod_unload ARMv6 p2v8 '
ipv6: version magic '4.4.34+ mod_unload modversions ARMv6 ' should be '4.4.34+ mod_unload ARMv6 p2v8 '
rfkill: version magic '4.4.34+ mod_unload modversions ARMv6 ' should be '4.4.34+ mod_unload ARMv6 p2v8 '
serio: version magic '4.4.34+ mod_unload modversions ARMv6 ' should be '4.4.34+ mod_unload ARMv6 p2v8 '
sg: version magic '4.4.34+ mod_unload modversions ARMv6 ' should be '4.4.34+ mod_unload ARMv6 p2v8 '
```

The version magic issue is easy enough to fix. By compiling the kernel myself using the script in the `tools` directory and changing the following options (using menuconfig), I was able to get a kernel that matches the version magic of the raspbian modules:
```
# Needed to show CONFIG_ARM_PATCH_PHYS_VIRT in the menu
CONFIG_EMBEDDED=y
# Manually disabled this on top level
# CONFIG_ARM_PATCH_PHYS_VIRT is not set
# needed when p2v8 is unset
CONFIG_PHYS_OFFSET=0x0
# manually enabled
CONFIG_MODVERSIONS=y
```

That gets rid of the version magic mismatch, but shows a modversion mismatch (since we've just enabled modversion check) and a new error message in the syslog:
```
pi@raspberrypi:~ $ sudo modprobe ipv6
modprobe: ERROR: could not insert 'ipv6': Exec format error
pi@raspberrypi:~ $ tail -1 /var/log/syslog
Jan 24 22:08:47 raspberrypi kernel: ipv6: disagrees about version of symbol module_layout
```

Even trying to stubbornly ignore any version mismatch by using `modprobe -f ipv6` still displays the exec format error, which is better than blindly crashing the kernel.

I don't know if it's possible to configure the kernel such that it is binary compatible with the stock raspbian modules. One could try and match the config as closely as possible to the raspbian kernel, but that may not be sufficient. We do need the kernel to be different for qemu after all.

I can think of two possible solutions:
* Enable support for `ipv6` in the kernel (not as a module). 
* Compile `ipv6` as a module and replace the raspbian version in the image

Tried both options successfully, i.e. `ping6 localhost` works. How useful it is inside qemu, I'm not sure.

**Comment by alexAubin** [comment]
Thanks a lot for investigating the issue !

What do you mean by "Enable support for ipv6 in the kernel (not as a module)." ? Is that related to the flags when compiling the kernel ?

**Comment by phildubach** [comment]
Yes, it's one of the many options you can enable when compiling the kernel. IPv6 support can either be statically compiled into the kernel (making the kernel bigger and wasting memory if IPv6 isn't needed) or as a loadable kernel module.

I believe that when I built the kernel with include IPv6 support, I still saw startup messages saying that the IPv6 module could not be loaded. I'll double-check tomorrow. Not an issue if you don't care about the error appearing in the log, or if you know where in the startup files to disable automatic loading of the module. There is an ipv6 specific file in `etc/modprobe.d/ipv6.conf`. Not sure if that's triggering the load attempt.

For my specific problem (which isn't actually ipv6, but other networking modules required for running docker), I will figure out what features I need and compile them as modules, then replace them in the image. It's a bit more painful, but it will then be the same mechanism as on a regular raspbian, so hopefully less compatibility issues.

If it's of any help to you, @alexAubin, I can publish my kernel with ipv6 somewhere for you to download.

**Comment by dhruvvyas90** [comment]
@phildubach: If you can create a PR with your kernel with IPv6 enabled, that would be great.

**Comment by dhruvvyas90** [comment]
@alexAubin: Did comments by phildubach help you solve your problem ? If yes, you can add a wiki and possibly your own derived kernel with IPv6 enabled to this repo. Thanks, - Dhruv.

**Comment by alexAubin** [comment]
Eeeeeh kind of, but I've never compiled that kind of kernel so I expect it's going to take me some times to be able to set it up if I start digging it. And I don't have so much time to invest in this right now :/ For now my dirty work around was to disable IPv6 stuff on the services that needed it (nginx, dovecot...), which is quite dirty for my application but does the job :/. Sorry for not being able to help more...

**Comment by dhruvvyas90** [comment]
I am closing this issue as I'll try to fix this issue with newer kernel if possible.
